services:
  postgres:
    image: postgres:17.5
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    ports:
      - ${DB_PORT_OUTER}:${DB_PORT_INNER}
    volumes:
      - db:/var/lib/postgres/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  jaeger:
    image: jaegertracing/jaeger:2.8.0
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "5778:5778"
      - "9411:9411"
    environment:
      - LOG_LEVEL=debug
volumes:
  db:
    driver: local
