[project]
name = "sample"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dtorannpu", email = "dtorannpu@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/sample"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
    "integration",
]

